### ISSUE TITLE
Next version to include updated dependencies?

### ISSUE THREAD

**Issue by davidbarratt** [minkphp/MinkGoutteDriver#63]
What is the next stable release version number that will include the updated dependencies?
https://github.com/minkphp/MinkGoutteDriver/commit/44563f46fa99fef2df50ce083048094828e068b7

I'm asking for:
https://www.drupal.org/node/2493911#comment-10096820

**Comment by aik099** [comment]
Unfortunately not before Guzzle 6 or Goutte 3 will fix issue with cookie handling. You can see failed build here: https://travis-ci.org/minkphp/MinkGoutteDriver

I'm not such one (Guzzle or Goutte) has a bug.

**Comment by davidbarratt** [comment]
@aik099,

I'm sorry, what I meant is not _when_, but _what_ version. Is the next version to include the dependencies going to be `1.1.2`, `1.3.0`, `2.0.0` ?

**Comment by aik099** [comment]
Theoretically dependency change should be considered as reason to have `1.3.0`, but I'm not 100% certain.

**Comment by davidbarratt** [comment]
@aik099,

Thanks! I updated our ticket to reflect that:
https://www.drupal.org/node/2493911#comment-10100368

**Comment by aik099** [comment]
Ah that's why you've asked about version :smile: . Then I'm afraid your suggestion for `^1.3.0` version won't get you `master` branch of this repo.

To make this happen a branch alias in `composer.json` needs to be changed to `1.3.x-dev`. @stof am I right in assuming, that next release would be 1.3.0?

**Comment by davidbarratt** [comment]
@aik099,

A branch alias in your `composer.json` or Drupal's?

**Comment by aik099** [comment]
This repo one. Because we're talking about this repo version usage on Drupal's side.

**Comment by davidbarratt** [comment]
@aik099,

Well now that you know what we're trying to do, any help would be greatly appreciated. :)

**Comment by aik099** [comment]
Based on Drupal task title you're updating to latest version of everything. Any specific need or just for fun?

**Comment by davidbarratt** [comment]
@aik099,

We're trying to update Guzzle to the latest stable release to satisfy this issue:
https://www.drupal.org/node/2400407

**Comment by davidbarratt** [comment]
@aik099,

With only 15 critical issues remaining, we are getting close to a release candidate of Drupal 8
https://www.drupal.org/project/issues/search/drupal?status[0]=1&status[1]=13&status[2]=8&status[3]=14&status[4]=4&priorities[0]=400&categories[0]=1&categories[1]=2&categories[2]=5&version[0]=8.x

**Comment by aik099** [comment]
OK. We'll waiting for @stof then to know the next version number of MinkGoutteDriver.

**Comment by stof** [comment]
1.2.0 has been released
