### ISSUE TITLE
Support basic auth parameters in URL

### ISSUE THREAD

**Issue by cweiske** [minkphp/MinkGoutteDriver#76]
I can use URLs with username and password fine with the selenium2 driver (and Firefox behind that), but goutte does not support it:

    $session->visit('https://username:password@example.org');
    echo $session->getPage()->getContent();

goutte has "401 Unauthorized" page content, selenium2 has the correct content. It would be nice if basic auth parameters would be extracted from the URL.

**Comment by aik099** [comment]
Fact, that it works for Selenium is nice, but we haven't added any code for it to work 😉 .

I recommend using official API (the `setBasicAuth` method) for specifying access credentials prior to visiting the page.

**Comment by cweiske** [comment]
`setBasicAuth` fails for selenium2, so I have the option to have non-working tests with goutte or non-working tests with selenium2.

Also, specifying the basic auth parameters in the URL is much easier/more convenient than in every test (using phpunit-mink)

**Comment by aik099** [comment]
Would you then send PRs for all other supported drivers + add tests to driver test suite to verify that auth parameter passing in urls works for everyone?

**Comment by cweiske** [comment]
Auth parameter test: https://github.com/minkphp/driver-testsuite/pull/15

**Comment by cweiske** [comment]
For some reason, the goutte driver here at home supports basic auth in the URL. At work it did not..

**Comment by aik099** [comment]
Maybe you're using different versions of the driver?

**Comment by cweiske** [comment]
I now found out what the problem is, and why my patch makes it work:

- My test fetches an URL with username+password
- That page redirects to a login page 
- Goutte - or rather Guzzle - does not use the basic auth data in the second request, which is why it fails and it seemed that it did not work at all.
- My patch converts URL data into session basic auth info that is used for every request, so it worked.

I do not know who should be responsible to keep basic auth data across requests (Goutte, BrowserKit, Guzzle).

**Comment by aik099** [comment]
> I do not know who should be responsible to keep basic auth data across requests (Goutte, BrowserKit, Guzzle).

It depends on what is documented behavior for each.

* since the mink drivers have dedicated method for setting user/pass for basic auth, then other means aren't officially supported
* I have no idea about goutte/guzzle

We surely need to read the docs of each to get the idea.

**Comment by cweiske** [comment]
I think this should be put into that layer that provides cookie storage across requests. Keeping basic auth data is the same category.
