### ISSUE TITLE
Compatibility with Goutte 4.x

### ISSUE THREAD

**Issue by lstrojny** [minkphp/MinkGoutteDriver#85]
ATM 3.1 is supported maximally, would be cool if 4.x would be supported

**Comment by aik099** [comment]
What is ATM, surely not a cashing machine?

**Comment by francislavoie** [comment]
ATM means "at the moment".

I'm also running into issues with this, I'm trying to update Guzzle to v7, but since this requires Goutte 3.x which still uses Guzzle (and requires v6), there's a dependency conflict.

**Comment by aik099** [comment]
PR's are welcome.
