### ISSUE TITLE
Add support for Symfony 5.

### ISSUE THREAD

**Issue by sveneld** [minkphp/MinkGoutteDriver#92]
Dependency behat/mink-browserkit-driver was updated at 13 December 2021 to version 2.0 which support Symfony 5. Please update this dependency in your composer.json

**Comment by aik099** [comment]
Might be connected to #91.

**Comment by yeroon** [comment]
I just ran into the same problem

**Comment by aik099** [comment]
Time for a PR.

**Comment by stof** [comment]
I have the work half done locally already.

**Comment by sveneld** [comment]
When new tag will be released?

**Comment by stof** [comment]
@sveneld now.
